---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-app
  namespace: prod
  labels:
    app: deploy-app
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: deploy-app
  template:
    metadata:
      labels:
        app: deploy-app
    spec:
      securityContext:
        runAsUser: 2000
        runAsGroup: 2000
        privileged: false
        runAsNonRoot: True
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
      containers:
      - name: conteiner-app
        image: image:v1
        resources:
          requests:
            cpu: "250m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 1
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 1

