---
apiVersion: v1
kind: LimitRange
metadata:
  name: lr-app
  namespce: prod
spec:
  limits:
  - type: Container
    max:
      cpu: 1
      memory: 1Gi
    min:
      cpu: 50m
      memory: 64Mi
    default:
      cpu: 100m
      memory: 128Mi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
  - type: Pod
    maxLimitRequestRatio:
      cpu: 2
      memory: 2
