---
apiVersion: v1
kind: LimitRange
metadata:
  name: lr-app
  namespce: prod
spec:
  limits:
  - type: Container
    max:
      cpu: 500m
      memory: 256Mi
    min:
      cpu: 250m
      memory: 128Mi
    default:
      cpu: 250m
      memory: 128Mi
    defaultRequest:
      cpu: 250m
      memory: 128Mi
  - type: Pod
    maxLimitRequestRatio:
      cpu: 2
      memory: 2
