---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: rq-app
  namespace: prod
spec:
  hard:
    limits.cpu: 4
    limits.memory: 1Gi
    requests.cpu: 4
    requests.memory: 1Gi
    pods: 4
    services: 1
    services.loadbalancers: 0
    services.nodeports: 0
    replicationcontrollers: 0
